### ISSUE TITLE
Single duplicate image results in Md5 message for all images

### ISSUE THREAD

**Issue by bhost909** [gmanley/loggia#7]
![Capture](https://f.cloud.github.com/assets/2023289/20153/22bd9234-4945-11e2-8771-d59a81491338.JPG)

When uploading a batch of images where only one image has already been uploaded, all of the images in the batch get marked with an Md5 duplicate message. The new images still get uploaded correctly. Maybe limit the duplicate message just to the image that is the duplicate?

**Comment by gmanley** [comment]
Fixed.
